# Generated by Django 5.1.3 on 2025-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='juegos/')),
                ('montos', models.JSONField(help_text='Lista de montos disponibles en formato JSON (e.g., [5, 10, 20])')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
