# Generated by Django 5.1.3 on 2025-01-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_montos_juegorecarga_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegorecarga',
            name='monto',
        ),
        migrations.AddField(
            model_name='juegorecarga',
            name='montos',
            field=models.JSONField(default=5, help_text='Lista de montos disponibles en formato JSON (e.g., [5, 10, 20])'),
            preserve_default=False,
        ),
    ]
