# Generated by Django 5.1.3 on 2025-01-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_juegorecarga_monto_juegorecarga_montos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegorecarga',
            old_name='montos',
            new_name='monto',
        ),
    ]
