# Generated by Django 5.1.3 on 2025-02-08 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_alter_usuario_managers_remove_codigogiftcard_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigogiftcard',
            name='usuario_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL),
        ),
    ]
