# Generated by Django 5.1.3 on 2025-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_codigogiftcard_usuario_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigogiftcard',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
