# Generated by Django 5.1.3 on 2025-02-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_codigoenviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoenviado',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codigoenviado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
