# Generated by Django 5.1.3 on 2025-02-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_codigoenviado_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoenviado',
            name='Tarjeta',
        ),
    ]
