# Generated by Django 5.1.3 on 2025-02-21 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigogiftcard',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='codigogiftcard',
            name='usuario_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='tarjeta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard', to='productos.tarjeta'),
        ),
    ]
