# Generated by Django 5.1.3 on 2025-02-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_compra_detalles_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='giftcard',
        ),
        migrations.AddField(
            model_name='compra',
            name='giftcards',
            field=models.ManyToManyField(to='productos.giftcard'),
        ),
    ]
