# Generated by Django 5.1.3 on 2025-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_remove_compra_giftcard_compra_giftcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='tipo',
            field=models.CharField(choices=[('playstation', 'PlayStation Gift Card USA'), ('nintendo', 'Nintendo Gift Card USA'), ('steam', 'STEAM USA'), ('itunes', 'ITUNES USA'), ('xbox', 'XBOX USA'), ('roblox', 'ROBLOX'), ('google_play', 'GOOGLE PLAY')], default='playstation', max_length=50),
        ),
    ]
