# Generated by Django 5.1.3 on 2025-01-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_juegorecarga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegorecarga',
            old_name='montos',
            new_name='monto',
        ),
    ]
