# Generated by Django 5.1.3 on 2025-02-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_tarjeta_remove_codigogiftcard_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigogiftcard',
            old_name='price',
            new_name='prices',
        ),
    ]
