# Generated by Django 5.1.3 on 2025-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_rename_price_codigogiftcard_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigogiftcard',
            name='codigo',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
