# Generated by Django 5.1.3 on 2025-02-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_codigogiftcard_codigo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
