# Generated by Django 5.1.3 on 2025-02-07 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='codigogiftcard',
            name='prices',
        ),
        migrations.AlterField(
            model_name='codigogiftcard',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='productos.tarjeta'),
        ),
        migrations.AlterField(
            model_name='codigogiftcard',
            name='usuario_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigogiftcard',
            name='prices',
            field=models.ManyToManyField(related_name='codigos', to='productos.price'),
        ),
    ]
