# Generated by Django 5.1.3 on 2025-02-10 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_codigogiftcard_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.transaction'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='tarjeta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giftcards', to='productos.tarjeta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='fecha_transaccion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
