# Generated by Django 5.1.3 on 2025-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_remove_codigoenviado_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigogiftcard',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
