# Generated by Django 5.1.3 on 2025-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_compra_codigos_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='detalles_compra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
